create table customer
(
    id              bigint generated by default as identity primary key,
    first_name      varchar(200),
    last_name       varchar(200),
    email           varchar(200),
    phone           varchar(20),
    activation_code varchar(200),
    password        varchar(200),
    created_at      timestamp
);
insert into customer(first_name, last_name, email, phone, activation_code, password, created_at)
values ('test', 'test', 'test@test.com', '+38555555555', 'activationCode', '123456', '2022-04-18');