drop table if exists customer ;
drop table if exists  roles;
CREATE TYPE role_enum AS ENUM ('USER', 'ADMIN');
create table customer
(
    id              bigint generated by default as identity primary key,
    first_name      varchar(200),
    last_name       varchar(200),
    email           varchar(200),
    phone           varchar(20),
    activation_code varchar(200),
    password        varchar(200),
    created_at      timestamp
);
create table customer_role
(
    customer_id bigint not null,
    roles       varchar(200)
);
alter table if exists customer_role
    add constraint customer_fk_role_key
        foreign key (customer_id) references customer (id);
insert into customer (id, first_name, last_name, email, phone, activation_code, password, created_at)
values (0, 'admin', 'admin', 'admin@admin.com', '48543493', '12345', 'admin', '2023-04-18');

create extension if not exists pgcrypto;

insert into customer_role(customer_id, roles)
values (0, 'ADMIN');
