CREATE TABLE category
(
    id   bigint generated by default as identity primary key,
    name VARCHAR(255) not null
);
CREATE TABLE producer
(
    id   bigint generated by default as identity primary key,
    name VARCHAR(255) not null
);

create table product
(
    id                bigint generated by default as identity primary key,
    name              varchar(200) not null,
    short_description varchar(200),
    long_description  varchar(2000),
    price             float(2),
    is_available      bool,
    quantity          int4,
    image             oid,
    content_type      varchar(40),
    category_id       bigint references category (id),
    producer_id       bigint references producer (id)
);
