version: '3.1'
services:
  project:
    container_name: project-container
    image: springboot-postgresql
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shopDb
    restart: always
