spring:
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/shopDb
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  flyway:
    url: jdbc:postgresql://postgresqldb:5432/shopDb
    user: postgres
    password: postgres
    locations: db/migration
    baseline-on-migrate: true
server:
  port: 9090