spring:
  config:
    import: classpath:secret.yml
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/shopDb
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  mail:
    port: 465
    host: smtp.gmail.com
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
    protocol: smtps
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  flyway:
    url: jdbc:postgresql://postgresqldb:5432/shopDb
    user: postgres
    password: postgres
    locations: db/migration
    baseline-on-migrate: true
server:
  port: 9090
mail:
  debug: true
frontend_url: localhost:8080